@extends('layouts.master')

@section('content')
<section id="gallery" class="gallery section-bg">
    <div class="container aos-init aos-animate" data-aos="fade-up">

      <div class="section-header">

        <p>Check <span>Our Gallery</span></p>
      </div>

      <div class="gallery-slider swiper swiper-initialized swiper-horizontal swiper-pointer-events">
        <div class="swiper-wrapper align-items-center" id="swiper-wrapper-72c438835cc29f98" aria-live="off" style="transition-duration: 0ms; transform: translate3d(-764.8px, 0px, 0px);"><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="3" role="group" aria-label="4 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-4.jpg"><img src="{{asset('assets/img/gallery/gallery-4.jpg')}}" class="img-fluid" alt=""></a></div><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="4" role="group" aria-label="5 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-5.jpg"><img src="{{asset('assets/img/gallery/gallery-5.jpg')}}" class="img-fluid" alt=""></a></div><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="5" role="group" aria-label="6 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-6.jpg"><img src="{{asset('assets/img/gallery/gallery-6.jpg')}}" class="img-fluid" alt=""></a></div><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="6" role="group" aria-label="7 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-7.jpg"><img src="{{asset('assets/img/gallery/gallery-7.jpg')}}" class="img-fluid" alt=""></a></div><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="7" role="group" aria-label="8 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-8.jpg"><img src="{{asset('assets/img/gallery/gallery-8.jpg')}}" class="img-fluid" alt=""></a></div>
          <div class="swiper-slide swiper-slide-prev" data-swiper-slide-index="0" role="group" aria-label="1 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-1.jpg"><img src="{{asset('assets/img/gallery/gallery-1.jpg')}}" class="img-fluid" alt=""></a></div>
          <div class="swiper-slide swiper-slide-active" data-swiper-slide-index="1" role="group" aria-label="2 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-2.jpg"><img src="{{asset('assets/img/gallery/gallery-2.jpg')}}" class="img-fluid" alt=""></a></div>
          <div class="swiper-slide swiper-slide-next" data-swiper-slide-index="2" role="group" aria-label="3 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-3.jpg"><img src="{{asset('assets/img/gallery/gallery-3.jpg')}}" class="img-fluid" alt=""></a></div>
          <div class="swiper-slide" data-swiper-slide-index="3" role="group" aria-label="4 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-4.jpg"><img src="{{asset('assets/img/gallery/gallery-4.jpg')}}" class="img-fluid" alt=""></a></div>
          <div class="swiper-slide" data-swiper-slide-index="4" role="group" aria-label="5 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-5.jpg"><img src="{{asset('assets/img/gallery/gallery-5.jpg')}}" class="img-fluid" alt=""></a></div>
          <div class="swiper-slide" data-swiper-slide-index="5" role="group" aria-label="6 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-6.jpg"><img src="{{asset('assets/img/gallery/gallery-6.jpg')}}" class="img-fluid" alt=""></a></div>
          <div class="swiper-slide" data-swiper-slide-index="6" role="group" aria-label="7 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-7.jpg"><img src="{{asset('assets/img/gallery/gallery-7.jpg')}}" class="img-fluid" alt=""></a></div>
          <div class="swiper-slide" data-swiper-slide-index="7" role="group" aria-label="8 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-8.jpg"><img src="{{asset('assets/img/gallery/gallery-8.jpg')}}" class="img-fluid" alt=""></a></div>
        <div class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-prev" data-swiper-slide-index="0" role="group" aria-label="1 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-1.jpg"><img src="{{asset('assets/img/gallery/gallery-1.jpg')}}" class="img-fluid" alt=""></a></div><div class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-active" data-swiper-slide-index="1" role="group" aria-label="2 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-2.jpg"><img src="{{asset('assets/img/gallery/gallery-2.jpg')}}" class="img-fluid" alt=""></a></div><div class="swiper-slide swiper-slide-duplicate swiper-slide-duplicate-next" data-swiper-slide-index="2" role="group" aria-label="3 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-3.jpg"><img src="{{asset('assets/img/gallery/gallery-3.jpg')}}" class="img-fluid" alt=""></a></div><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="3" role="group" aria-label="4 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-4.jpg"><img src="{{asset('assets/img/gallery/gallery-4.jpg')}}" class="img-fluid" alt=""></a></div><div class="swiper-slide swiper-slide-duplicate" data-swiper-slide-index="4" role="group" aria-label="5 / 8" style="width: 171.2px; margin-right: 20px;"><a class="glightbox" data-gallery="images-gallery" href="assets/img/gallery/gallery-5.jpg"><img src="{{asset('assets/img/gallery/gallery-5.jpg')}}" class="img-fluid" alt=""></a></div></div>
        <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets swiper-pagination-horizontal"><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 1"></span><span class="swiper-pagination-bullet swiper-pagination-bullet-active" tabindex="0" role="button" aria-label="Go to slide 2" aria-current="true"></span><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 3"></span><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 4"></span><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 5"></span><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 6"></span><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 7"></span><span class="swiper-pagination-bullet" tabindex="0" role="button" aria-label="Go to slide 8"></span></div>
      <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span></div>

    </div>
  </section>
@endsection
